name: 4 GPU Unit Test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.g5.12xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: "12.1"
      # Trying how much faster the nvidia-cuda image is
      docker-image: "nvidia/cuda:12.4.1-runtime-ubuntu22.04"
      repository: "pytorch/torchtitan"
      upload-artifact: "outputs"
        # conda create -n "test" python=3.10
        # conda activate test
      script: |
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm -rf ~/miniconda3/miniconda.sh
        ~/miniconda3/bin/conda init bash
        conda install -y -q git clang clangxx cxx-compiler
        export CC=clang
        export CXX=clangxx
        pip config --user set global.progress_bar off
        pip install --upgrade pip
        python -m pip install --force-reinstall --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
        python -m pip install -r requirements.txt
        python -m pip install -r dev-requirements.txt
        python -m pip install git+https://github.com/pytorch/pippy
        python ./test_runner.py
        mv outputs artifacts-to-be-uploaded
  # upload-coverage:
  #     - name: Upload Coverage to Codecov
  #       uses: codecov/codecov-action@v3
